services:
  - type: web
    name: youtube-downloader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env: python
    port: 10000  # Match the port in app.py